# -*- coding: utf-8 -*-
"""GRUmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgKyJJAUb-9wPl_PnfXe761ICIYTWM5h
"""

class GRUmodel(nn.Module):
    def __init__(self):
        super(GRUmodel, self).__init__()
        self.hidden_size = 64
        self.rnn = nn.GRU(
            input_size=300, hidden_size=self.hidden_size, batch_first=True, bidirectional=True
        )
        self.drop = nn.Dropout(0.5)
        self.fc = nn.Linear(4 * self.hidden_size, 1)

    def forward(self, x):
        out, _ = self.rnn(x)
        out = torch.cat([torch.max(out, dim=1)[0], torch.mean(out, dim=1)], dim=1)
        out = self.drop(out)
        out = self.fc(out)
        return torch.sigmoid(out)